### PR TITLE
Hw3hw4

### PR DESCRIPTION
**Pull request by Rauxx**
as requested in HW4

### CODE REVIEW

**Comment by Rauxx** [comment]
Is this better, I think I managed to do what you asked

**Comment by floridop** [comment]
Please read ALL of this message before deciding what to do.

Unfortunately I think you messed it up big time. You can check yourself what are the changed files in
https://github.com/floridop/MNXB01-2018/pull/31/files
You will see that your pull request is asking me to delete all my files and it is not asking me to add any of yours. This means you deleted all files from git. The files should not be deleted from the git database (git rm) but should simply be restored from my upstream repository one by one. The easiest is that you just copy them over manually the way they are online.

However looking  at your commit history in https://github.com/floridop/MNXB01-2018/pull/31/commits
I think you should just revert to your commit 32e168727b3cacb6726c792bb94945e698151332 , that was **perfect**. You can find how to revert to a previous commit in my slides, or maybe you can even do it from the github interface.
Regards,
Florido

**Comment by Rauxx** [comment]
Ok, so I’ll try to revert to that commit, got it.
One thing I am not sur of though, when I do the pull request should that be from my fork or your repository?
Best regards
Viktor Mårtensson
________________________________
Från: Florido Paganelli <notifications@github.com>
Skickat: Thursday, November 15, 2018 11:12:00 AM
Till: floridop/MNXB01-2018
Kopia: Rauxx; State change
Ämne: Re: [floridop/MNXB01-2018] Hw3hw4 (#31)


Please read ALL of this message before deciding what to do.

Unfortunately I think you messed it up big time. You can check yourself what are the changed files in
https://github.com/floridop/MNXB01-2018/pull/31/files
You will see that your pull request is asking me to delete all my files and it is not asking me to add any of yours. This means you deleted all files from git. The files should not be deleted from the git database (git rm) but should simply be restored from my upstream repository one by one. The easiest is that you just copy them over manually the way they are online.

However looking at your commit history in https://github.com/floridop/MNXB01-2018/pull/31/commits
I think you should just revert to your commit 32e1687<https://github.com/floridop/MNXB01-2018/commit/32e168727b3cacb6726c792bb94945e698151332> , that was perfect. You can find how to revert to a previous commit in my slides, or maybe you can even do it from the github interface.
Regards,
Florido

**Comment by Rauxx** [comment]
I think I managed to what was asked (reverted to 32e1687) and made a pull request, not sure if it is correct though

**Comment by floridop** [comment]
Hi Viktor,
This did not work either. I asked you to check the changes page,
https://github.com/floridop/MNXB01-2018/pull/31/files
I think your changes happened before that commit, so reverting them is a bit more complicated.
I think is totally out of time now, I am forced to close this merge request as is. I will use your fork to correct the HW3 homework.

**Pull request closed without merging**
