### PR TITLE
Here is my incomplete HW3 that has already been submitted through liv…

### PR DESCRIPTION
**Pull request by taichi333**
…e@lund

### CODE REVIEW

**Comment by taichi333** [comment]
https://github.com/floridop/MNXB01-2018/pull/24

**Comment by taichi333** [comment]
https://github.com/taichi333/MNXB01-2018

**Comment by floridop** [comment]
Hi Taichi. Could you please submit the two links to Live at Lund in HW4? 
Otherwise I cannot grade you in the system.
Both links look good so you should!
As per HW3, I will correct it soon.
I will not perform the merge request if you don't do and then you will NOT get any grade, so please take action. All Homework is mandatory.

**Comment by taichi333** [comment]
Hello Florido,

I'll submit the file after my final exam tomorrow morning. Sorry for the
inconveniences.

Thank you,
Taichi Ito

**Comment by floridop** [comment]
No worries, you have time for this HW4 until 2018/11/08. Best of luck with the exam!

**Comment by floridop** [comment]
Hi Taichi! How is it going? Could you take care of this by the day?

**Comment by taichi333** [comment]
Hello!!
I'm sorry it took so long! I'll send it in right now!

**Comment by floridop** [comment]
I still see no changes.

**Comment by floridop** [comment]
Hi Taichi,
I'm sorry but this dragged for too long. I will close this pull request and use your fork to correct your HW3.
Regards,
Florido

**Pull request closed without merging**
