### PR TITLE
hw3hw4 pull request

### PR DESCRIPTION
**Pull request by em5728jo-s**
Emil Johansson pull request for homework 4.

### CODE REVIEW

**Comment by em5728jo-s** [comment]
I have now done the steps you requested, tell me if anything else has to be done.

**Comment by floridop** [comment]
Hi Emil! something went wrong, it still shows me `floridopag/HW3/fortuneteller.sh` as created in my own directory. Are you sure you pushed to the right branch? 

I think the default of `git push` is to push to master, sorry I should have taken more care when writing instructions. The correct thing to do is

```shell 
git checkout hw3hw4
git rm floridopag/HW3/fortuneteller.sh
git commit -m 'Removing files from floridos folder'
git push origin hw3hw4
```

**Comment by em5728jo-s** [comment]
It should be fixed now. Again, contact me if there seems to be any other problems.

**Comment by floridop** [comment]
All good thanks!

**Pull request merged**
